---
# utsusemi service name
serviceName: utsusemi
# AWS deploy region
region: ap-northeast-1
# Crawl target host
targetHost: https://opslet.com
# Web site hosting S3 bucket name
bucketName: utsusemi.opslet.com
# Crawl worker process
workerProcess: 2
# Delay time when start worker (ms)
workerDelay: 100
# Crawl job threads per worker
threadsPerWorker: 1
# Change http://example.com/path/to -> http://example.com/path/to/
forceTrailingSlash: 1
# Create link with Query String
withQueryString: 0
# Use API Key when request utsusemi API
useApiKey: 0
# Crawler User Agent
# crawlerUserAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 +utsusemi'
