---
region: ap-northeast-1
targetHost: https://opslet.com
bucketName: utsusemi.opslet.com
workerProcess: 2
workerDelay: 100
threadsPerWorker: 1
# crawlerUserAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 +utsusemi'
